#!/bin/bash

green=$(tput setaf 2)
red=$(tput setaf 1)
normal=$(tput sgr0)

BLEU='\033[0;34m'
GREEN='\033[0;32m'
LGREY='\033[0;37m'
RED='\033[0;31m'
NC='\033[0m'

sender=$(sudo grep mailsender /usr/share/urnis/src/urnis.conf | cut -c 13- | sed 's/"//g')
passw=$(sudo grep password /usr/share/urnis/src/urnis.conf | cut -c 10- | sed 's/"//g')
reciver=$(sudo grep mailreciver /usr/share/urnis/src/urnis.conf | cut -c 13- | sed 's/"//g')
tim=$(sudo grep timet /usr/share/urnis/src/urnis.conf | cut -c 7- | sed 's/"//g')
up=$(sudo grep aptupdate /usr/share/urnis/src/urnis.conf | cut -c 11- | sed 's/"//g')
pathfilemail="/usr/share/urnis/data/audit"
totaltest=0
war=0
reco=0

pathaudit="/usr/share/urnis/data/audit"
pathlog="/usr/share/urnis/data/log"
pathreco="/usr/share/urnis/src/recommandation.txt"
cmdt="/usr/share/urnis/data/tmpwc"




helper () {
    echo -e "${LGREY}[ Urnis 1.0.0 ]${NC}\n\n"

    echo -e "   ${BLEU}Description${NC}"
    printf "       Urnis is a script that performs a security audit of your system.\n\n"

    echo -e "   ${BLEU}Usage${NC}"
    echo -e "       sudo urnis OPTION"

    echo -e "\n\n   ${BLEU}Option${NC}"
    printf "%-20s %-20s %s\n" "       OPTION" "NAME" "DESCRIPTION"
    printf "%-20s %-20s %s\n" "       -a" "audit" "make audit of your system"
    printf "%-20s %-20s %s\n" "       -h" "help" "usage of urnis"
    printf "%-20s %-20s %s\n" "       -u" "update" "update of Urnis"
    printf "%-20s %-20s %s\n" "       -l &" "look" "generation of an audit every 12 hours automatically"
    printf "%-20s %-20s %s\n" "       -m" "audit mail" "make audit of your system and send it by email"
    printf "%-20s %-20s %s\n" "       -r" "remove" "remove all files of urnis"
    printf "%-20s %-20s %s\n" "       -k" "kill look" "kill look mode process"
    printf "%-20s %-20s %s\n" "       -s" "status" "status of look mode"

    echo -e "\n\n   ${BLEU}Configuration${NC}"
    printf "%-41s %s\n" "       Configure mail" "/usr/share/urnis/src/urnis.conf"
    printf "%-41s %-20s %s\n" "       Add programs to check" "/usr/share/urnis/src/pro.txt"
    printf "%-41s %-20s %s\n" "       Add directories to check" "/usr/share/urnis/src/dir.txt"
    printf "%-41s %-20s %s\n" "       Enable apt update in look mode" "/usr/share/urnis/src/urnis.conf"


    echo -e "\n\n   ${BLEU}Author${NC}"
    printf "%-20s %s\n" "       github" "https://github.com/bubudotsh/urnis-secutity"
    printf "%-20s %s\n" "       developper" "BUNELIER Hugo"
    echo -e "\n"
}




check () {
    echo -e "\n\n${BLEU}[+] CHECK FILE AND DIR${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    if [ -f "/etc/ssh/sshd_config" ] && [ -f "/etc/shadow" ] && [ -f "/etc/sudoers" ] && [ -f "/etc/os-realease" ]; then
        printf "%-45s %s\n" "   file require" "${green}OK${normal}"
        sudo sed -i -e 's/#d_os_detection/d_os_detection/g'
        
    else
        printf "%-45s %s\n" "   file require" "${red}WARNING${normal}"
    fi

    if [ -f "/usr/share/urnis/src/urnis.conf" ] && [ -f "/usr/share/urnis/src/dir.txt" ] && [ -f "/usr/share/urnis/src/MD5Hahses.txt" ]; then
        printf "%-45s %s\n" "   urnis file" "${green}OK${normal}" 
    else
        printf "%-45s %s\n" "   urnis file" "${red}WARNING${normal}"
    fi
}

d_os_detection () {
    printf "%-45s %s\n" "   System" "$(egrep '^(NAME)=' /etc/os-release | cut -c 7- | sed 's/"//g')" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   Version" "$(egrep '^(VERSION)=' /etc/os-release | cut -c 9- | sed 's/"//g')" 2>&1 | tee -a ${pathlog}
}

os_detections() {
    echo -e "${BLEU}[+] OS detections${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    #d_os_detection
    printf "%-45s %s\n" "   Kernel" "$(uname -r)" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   IP" "$(hostname -I)" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   Name" "$(hostname)" 2>&1 | tee -a ${pathlog}
}



while getopts "huamlrks" option; do
case $option in
    h)
        helper
        exit;;
    u)
        update
        exit;;
    a)
        check
        exit;;
    m)
        audit
        sudo python3 /usr/share/urnis/src/mailsender.py ${sender} ${passw} ${reciver} ${pathfilemail}
        exit;;
    l)
        look > /dev/null 2> /dev/null
        exit;;
    k)
        kills
        exit;;
    r)
        remove
        exit;;
    s)
        status
        exit;;
    \?)
        echo "bad option, help : -h"
        exit;;
    esac
done
echo "bad option, try sudo urnis -h"