#!/bin/bash

green=$(tput setaf 2)
red=$(tput setaf 1)
normal=$(tput sgr0)

BLEU='\033[0;34m'
GREEN='\033[0;32m'
LGREY='\033[0;37m'
RED='\033[0;31m'
NC='\033[0m'

sender=$(sudo grep mailsender /usr/share/urnis/src/urnis.conf | cut -c 13- | sed 's/"//g')
passw=$(sudo grep password /usr/share/urnis/src/urnis.conf | cut -c 10- | sed 's/"//g')
reciver=$(sudo grep mailreciver /usr/share/urnis/src/urnis.conf | cut -c 13- | sed 's/"//g')
tim=$(sudo grep timet /usr/share/urnis/src/urnis.conf | cut -c 7- | sed 's/"//g')
up=$(sudo grep aptupdate /usr/share/urnis/src/urnis.conf | cut -c 11- | sed 's/"//g')
date=$(date)
pathfilemail="/usr/share/urnis/data/audit"

pathaudit="/usr/share/urnis/data/audit"
pathlog="/usr/share/urnis/data/log"
pathreco="/usr/share/urnis/src/recommandation.txt"

helper () {
    echo -e "${LGREY}[ Urnis 1.0.0 ]${NC}\n\n"

    echo -e "   ${BLEU}Description${NC}"
    printf "       Urnis is a script that performs a security audit of your system.\n\n"

    echo -e "   ${BLEU}Usage${NC}"
    echo -e "       sudo urnis OPTION"

    echo -e "\n\n   ${BLEU}Option${NC}"
    printf "%-20s %-20s %s\n" "       OPTION" "NAME" "DESCRIPTION"
    printf "%-20s %-20s %s\n" "       -a" "audit" "make audit of your system"
    printf "%-20s %-20s %s\n" "       -h" "help" "usage of urnis"
    printf "%-20s %-20s %s\n" "       -u" "update" "update of Urnis"
    printf "%-20s %-20s %s\n" "       -l &" "look" "generation of an audit every 12 hours automatically"
    printf "%-20s %-20s %s\n" "       -m" "audit mail" "make audit of your system and send it by email"
    printf "%-20s %-20s %s\n" "       -r" "remove" "remove all files of urnis"
    printf "%-20s %-20s %s\n" "       -k" "kill look" "kill look mode process"
    printf "%-20s %-20s %s\n" "       -s" "status" "status of look mode"

    echo -e "\n\n   ${BLEU}Configuration${NC}"
    printf "%-41s %s\n" "       Configure mail" "/usr/share/urnis/src/urnis.conf"
    printf "%-41s %-20s %s\n" "       Add programs to check" "/usr/share/urnis/src/pro.txt"
    printf "%-41s %-20s %s\n" "       Add directories to check" "/usr/share/urnis/src/dir.txt"
    printf "%-41s %-20s %s\n" "       Enable apt update in look mode" "/usr/share/urnis/src/urnis.conf"


    echo -e "\n\n   ${BLEU}Author${NC}"
    printf "%-20s %s\n" "       github" "https://github.com/bubudotsh/urnis-secutity"
    printf "%-20s %s\n" "       developper" "BUNELIER Hugo"
    echo -e "\n"
}


maj () {
    if [ "${up}" = "enable" ]; then
        echo -e "\n\n${BLEU}[+] MAJ SYSTEM${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
        (sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt update -y && sudo apt upgrade -y) > /usr/share/urnis/data/log-maj
        echo -e 'maj log aviable in /usr/share/urnis/data/log-maj \n' 2>&1 | tee -a ${pathlog}
    fi
}

firewall () {
    echo -e "\n\n${BLEU}[+] NETWORK${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    ufwcm=$(sudo ufw status | awk '{ print $2'})
    echo "   - Firewall" 2>&1 | tee -a ${pathlog}
    if command -v ufw > /dev/null 2>&1; then
        if [ "${ufwcm}" = "inactive" ] || [ "${ufwcm}" = "inactif" ]; then
            printf "%-45s %s\n" "       - ufw status" "${red}INACTIVE${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "* Active ufw" >> ${pathreco}
        else
            printf "%-45s %s\n" "       - ufw status" "${green}ACTIF${normal}" 2>&1 | tee -a ${pathlog}
        fi
        echo "ufw satus:       $(sudo ufw status | awk '{ print $2'})" >> ${pathaudit}
    else
        echo "      - ufw not found" 2>&1 | tee -a ${pathlog}
        echo "ufw not found" >> ${pathaudit}
    fi

    if command -v iptables > /dev/null 2>/dev/null; then
        iptablesst=$((sudo iptables -L) > /dev/null 2> /dev/null | grep INPUT)
        if [ "${iptablesst}" = "Chain INPUT (policy ACCEPT)" ];then
            printf "%-45s %s\n" "       - Iptables INPUT" "${red}ACCEPT${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "iptables INPUT   ACCEPT" >> ${pathaudit}
            echo -e "* Switch to DROP and create yours ruls" >> ${pathreco}
        elif [ "${iptablesst}" = "Chain INPUT (policy DROP)" ]; then
            printf "%-45s %s\n" "       - iptables INPUT" "${green}DROP${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "iptables INPUT   DROP" >> ${pathaudit}
        else
            printf "%-45s %s\n" "       - iptables INPUT" "${green}CUSTOM${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "iptables INPUT   CUSTOM" >> ${pathaudit}
        fi
    else
        echo "      - iptables not found" 2>&1 | tee -a ${pathlog}
        echo "iptables not found" >> ${pathaudit}
    fi

    if command -v netstat > /dev/null 2>&1; then
        openpor=$(sudo netstat -tulpn | wc -l)
        if [ 0 -lt $((${openpor} + 0)) ]; then
            printf "%-45s %s\n" "   - open port" "FOUND" 2>&1 | tee -a ${pathlog}
            echo -e "       - Result: $(sudo netstat -tulpn | wc -l)"
            echo "open port:       $(sudo netstat -tulpn | wc -l)" >> ${pathaudit}
            (echo -e "\n" ; sudo netstat -tulpn) >> ${pathlog}
        else
            printf "%-45s %s\n" "   - open port" "NOT FOUND" 2>&1 
        fi
    else
        echo "  - netstat not found" 2>&1 | tee -a ${pathlog}
    fi

    if command -v ip route > /dev/null 2>&1; then
        iproute=$(ip route | grep default | wc -l)
        if [ 0 -lt $((${openpor} + 0)) ]; then
            printf "%-45s %s\n" "   - network bridge" "${red}DEFAULT${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "* Switch to custom network bridge" >> ${pathreco}
        else
            printf "%-45s %s\n" "   - network bridge" "${green}CUSTOM${normal}" 2>&1 | tee -a ${pathlog}
        fi
    else
        echo "  - ip route not found" 2>&1 | tee -a ${pathlog}
    fi
}

scan () {
    echo -e "\n\n${BLEU}[+] SCAN FILES${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    echo -e "Scan directories file...\n" 2>&1 | tee -a ${pathlog}
    total_file=0
    suspect_file=0
    hashfile="/usr/share/urnis/src/MD5Hahses.txt"
    file_path="/usr/share/urnis/src/dir.txt"
    while read -r line; do
        if [ -d "$line" ]; then
            printf "%-45s" "   - Checking $line" 2>&1 | tee -a ${pathlog}
            if [ ! -f "$hashfile" ]; then
                echo "Hash file list not found" 2>&1 | tee -a ${pathlog}
                exit 1
            fi
            for file in "$line"/*; do
                if [ -d "$file" ]; then
                    echo -n
                else
                    file_hash=$(md5sum "$file" | cut -d' ' -f1)
                    match=$(grep "$file_hash" "$hashfile")
                    if [ -z "$match" ]; then
                        ((total_file=total_file+1))
                    else
                        printf "%-60s %s\n" " $file" "${red}SUSPECT${normal}" >> ${pathlog} 2>> ${pathlog}
                        echo -e "* Check $file possibility of malware" >> ${pathreco}
                        ((suspect_file=suspect_file+1))
                    fi
                fi
            done
            if [ "${suspect_file}" = 0 ]; then
                echo -e "${GREEN}OK${NC}" 2>&1 | tee -a ${pathlog}
            else
                echo -e "${RED}FOUND${NC}" 2>&1 | tee -a ${pathlog}
            fi
        else
            printf "%-45s %s\n" "   - Checking $line" "${red}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
            
        fi
    done < "$file_path"
    ((total_file=total_file+suspect_file))
    echo -e "suspect files:   $suspect_file" >> ${pathaudit}
    echo -e "total files:     $total_file" >> ${pathaudit}
}

os_detections() {
    echo -e "${BLEU}[+] OS detections${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   System" "$(egrep '^(NAME)=' /etc/os-release | cut -c 7- | sed 's/"//g')" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   Version" "$(egrep '^(VERSION)=' /etc/os-release | cut -c 9- | sed 's/"//g')" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   Kernel" "$(uname -r)" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   IP" "$(hostname -I)" 2>&1 | tee -a ${pathlog}
    printf "%-45s %s\n" "   Name" "$(hostname)" 2>&1 | tee -a ${pathlog}

    echo -e "System           $(egrep '^(NAME)=' /etc/os-release | cut -c 7- | sed 's/"//g')" >> ${pathaudit}
    echo -e "Version          $(egrep '^(VERSION)=' /etc/os-release | cut -c 9- | sed 's/"//g')" >> ${pathaudit}
    echo -e "Kernel           $(uname -r)" >> ${pathaudit}
    echo -e "IP               $(hostname -I)" >> ${pathaudit}
    echo -e "Name             $(hostname)" >> ${pathaudit}
}

prog () {
    echo -e "\n\n${BLEU}[+] RECOMANDED PROGRAMS${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    file_path="/usr/share/urnis/src/pro.txt"
    while read -r line; do
        if command -v $line > /dev/null 2>&1; then
            printf "%-45s %s\n" "   - $line" "${green}FOUND${normal}" 2>&1 | tee -a ${pathlog}
        else
            printf "%-45s %s\n" "   - $line" "${red}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "* Install ${line}" >> ${pathreco}
        fi
    done < "$file_path"
}

info () {
    echo "==================================================================================="
    echo -e "Urniscomes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under the terms of the GNU General
Public License.\n"
    printf "%-10s %s\n" "Creator:" "BUNELIER Hugo"
    printf "%-10s %s\n" "GitHub:" "https://github.com/bubudotsh/urnis-security"
    printf "%-10s %s\n" "Update:" "please check the update on the project's git hub for new functionality"
    echo -e "===================================================================================\n\n"
}

bootinfo () {
    echo -e "\n\n${BLEU}[+] BOOT INFO ${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    securebot=$(mokutil --sb-state)
    bootefi=$(ls /sys/firmware/efi > /dev/null 2> /dev/null ; echo "$?")
    if [ "$securebot" = "SecureBoot disabled" ]; then
        printf "%-45s %s\n" "   - Secure Boot" "${red}DISABLE${normal}" 2>&1 | tee -a ${pathlog}
        echo -e "* Active secure boot" >> ${pathreco}
    elif [ "$securebot" = "SecureBoot enabled" ];then
        printf "%-45s %s\n" "   - Secure Boot" "${green}ENABLED${normal}" 2>&1 | tee -a ${pathlog}
    else
        echo "${securebot}" 2>&1 | tee -a ${pathlog}
    fi
    if [ "$bootefi" = "0" ]; then
        printf "%-45s %s\n" "   - efi boot" "${green}ENABLED${normal}" 2>&1 | tee -a ${pathlog}
    else
        printf "%-45s %s\n" "   - efi boot" "${red}DISABLE${normal}" 2>&1 | tee -a ${pathlog}
    fi
}

reco () {
    echo -e "\n\n${BLEU}[+] RECOMMANDATION${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    sudo cat /usr/share/urnis/src/recommandation.txt 2>&1 | tee -a ${pathlog}
}

admin () {
    echo -e "\n\n${BLEU}[+] USERS AND SERVICES${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    emptypass=$(sudo getent shadow | grep ':!:' | cut -d: -f1 | wc -l)
    if [ 0 -lt $((${emptypass} + 0)) ];then
        printf "%-45s %s\n" "   - User with empty password" "${red}WARING${normal}"
        echo -e "       - Result: $(sudo getent shadow | grep ':!:' | cut -d: -f1 | wc -l)"
        echo "user with empty password" >> ${pathlog}
        sudo getent shadow | grep ':!:' | cut -d: -f1 >> ${pathlog}
    else
        printf "%-45s %s\n" "   - User with empty password" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
    fi
    echo "empty pass:      $(sudo getent shadow | grep ':!:' | cut -d: -f1 | wc -l)" >> ${pathaudit}

    admservice=$(sudo service --status-all | awk '{print $4}' | wc -l)
    if [ 0 -lt $((${admservice} + 0)) ];then
        printf "%-45s %s\n" "   - Admin services" "FOUND"
        echo -e "       - Result: $(sudo service --status-all | awk '{print $4}' | wc -l)"
        echo -e "\nAdmin services" >> ${pathlog}
        sudo service --status-all | awk '{print $4}' >> ${pathlog}
    else
        printf "%-45s %s\n" "   - admin services" "NOT FOUND" 2>&1 | tee -a ${pathlog}
    fi
    echo "admin service:   $(sudo service --status-all | awk '{print $4}' | wc -l)" >> ${pathaudit}

    if [ -f "/etc/sudoers" ]; then
        admright=$(sudo cat /etc/sudoers | grep '^%admin' | wc -l)
        if [ 0 -lt $((${admright} + 0)) ];then
            printf "%-45s %s\n" "   - User with admin right" "FOUND"
            echo -e "       - Result: $(sudo cat /etc/sudoers | grep '^%admin' | wc -l)"
            echo -e "\nuser with admin right" >> ${pathlog}
            sudo cat /etc/sudoers | grep '^%admin' >> ${pathlog}
        else
            printf "%-45s %s\n" "   - user with admin right" "NOT FOUND" 2>&1 | tee -a ${pathlog}
        fi
        echo "admin right:     $(sudo cat /etc/sudoers | grep '^%admin' | wc -l)" >> ${pathaudit}
    else
        echo "  - /etc/sudoers not found" 2>&1 | tee -a ${pathlog}
    fi

    passexp=$(awk -F: '($3 < 1000) {print}' /etc/shadow | wc -l)
    if [ 0 -lt $((${passexp} + 0)) ];then
        printf "%-45s %s\n" "   - passwords expired/nearing expiration" "${red}WARNING${normal}"
        echo -e "       - Result: ${passexp}"
        echo -e "\npasswords expired/nearing expiration" >> ${pathlog}
        awk -F: '($3 < 1000) {print}' >> ${pathlog}
    else
        printf "%-45s %s\n" "   - passwords expired/nearing expiration" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
    fi

    inna=$(cat /etc/shadow | grep ":!" | awk -F ":" '{print $1}' | wc -l)
    if [ 0 -lt $((${inna} + 0)) ];then
        printf "%-45s %s\n" "   - inactive user accounts" "${red}WARNING${normal}"
        echo -e "       - Result: ${inna}"
        echo -e "\ninactive user accounts" >> ${pathlog}
        cat /etc/shadow | grep ":!" | awk -F ":" '{print $1}' >> ${pathlog}
    else
        printf "%-45s %s\n" "   - inactive user accounts" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
    fi
}

software () {
    echo -e "\n\n${BLEU}[+] SOFTWARE${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    if [ -x "$(command -v apt-get)" ]; then
        soft1=$(apt-get dist-upgrade --dry-run | grep "^Inst" | awk '{print $2}' | wc -l)
        if [ 0 -lt $((${soft1} + 0)) ]; then
            printf "%-45s %s\n" "   - outdated software" "${red}WARING${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "       - result: ${soft1}"
            apt-get dist-upgrade --dry-run | grep "^Inst" | awk '{print $2}' >> ${pathlog}
        else
            printf "%-45s %s\n" "   - outdated software" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
        fi
    fi

    for user in $(cut -d: -f1 /etc/passwd); do
        if [ "$user" != "root" ] && [ -d "/home/$user" ]; then
            soft2=$(find "/home/$user" -type f -perm -u=x -print | wc -l)
            if [ 0 -lt $((${soft2} + 0)) ]; then
                printf "%-45s %s\n" "   - unauthorized executable files" "${red}WARING${normal}" 2>&1 | tee -a ${pathlog}
                echo -e "       - result: ${soft2}"
                find "/home/$user" -type f -perm -u=x -print >> ${pathlog}
            else
                printf "%-45s %s\n" "   - unauthorized executable files" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
            fi
        fi
    done

    soft3=$(sudo find / -type f -perm -4000 -exec ls -ld {} \; > /dev/null 2> /dev/null | wc -l)
    if [ 0 -lt $((${soft3} + 0)) ]; then
        printf "%-45s %s\n" "   - file with elevated permissions" "${red}WARING${normal}" 2>&1 | tee -a ${pathlog}
        echo -e "       - result: ${soft3}"
        sudo find / -type f -perm -4000 -exec ls -ld {} \; 2>> ${pathlog} >> ${pathlog}
    else
        printf "%-45s %s\n" "   - file with elevated permissions" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
    fi

    soft4=$(sudo find / -type f -perm -4000 -exec ls -ld {} \; > /dev/null 2> /dev/null | wc -l)
    if [ 0 -lt $((${soft4} + 0)) ]; then
        printf "%-45s %s\n" "   - directory with elevated permissions" "${red}WARING${normal}" 2>&1 | tee -a ${pathlog}
        echo -e "       - result: ${soft4}"
        sudo find / -type d -perm -4000 -exec ls -ld {} \; 2>> ${pathlog} >> ${pathlog}
    else
        printf "%-45s %s\n" "   - directory with elevated permissions" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
    fi

    soft5=$(systemctl list-units --all --type=service | grep "inactive" | wc -l)
    if [ 0 -lt $((${soft5} + 0)) ]; then
        printf "%-45s %s\n" "   - inactive services" "${red}WARING${normal}" 2>&1 | tee -a ${pathlog}
        echo -e "       - result: ${soft5}"
        systemctl list-units --all --type=service | grep "inactive" >> ${pathlog}
    else
        printf "%-45s %s\n" "   - inactive services" "${green}NOT FOUND${normal}" 2>&1 | tee -a ${pathlog}
    fi
}

sshcheck () {
    echo -e "\n\n${BLEU}[+] SSH CONFIG${NC}\n-----------------------------------\n" 2>&1 | tee -a ${pathlog}
    if [ -f '/etc/ssh/sshd_config' ]; then
        sshport=$(grep -iE 'port' /etc/ssh/sshd_config | grep 22 | wc -l)
        if [ 0 -lt $((${sshport} + 0)) ]; then
            printf "%-45s %s\n" "   - ssh port" "${red}DEFAULT${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "* change ssh port" >> ${pathreco}
        else
            printf "%-45s %s\n" "   - ssh port" "${green}CUSTOM${normal}" 2>&1 | tee -a ${pathlog}
        fi

        sshport=$(grep -iE 'permitrootlogin' /etc/ssh/sshd_config | grep no | wc -l)
        if [ 0 -eq $((${sshport} + 0)) ]; then
            printf "%-45s %s\n" "   - permit root login" "${red}WARING${normal}" 2>&1 | tee -a ${pathlog}
            echo -e "* put permit root login no" >> ${pathreco}
        else
            printf "%-45s %s\n" "   - permit root login" "${green}NO${normal}" 2>&1 | tee -a ${pathlog}
        fi
    else
        echo "/etc/ssh/sshd_config non found" 2>&1 | tee -a ${pathlog}
    fi
}

audit () {
    echo "" > /usr/share/urnis/src/recommandation.txt
    echo "" > /usr/share/urnis/data/log
    echo -e "${LGREY}[ Urnis 1.0.0 ]${NC}\n\n"
    echo -e "[ Urnis 1.0.0 ]\n\n" > ${pathaudit}
    info 2>&1 | tee -a ${pathlog}
    echo -e "------------------------------------" >>${pathaudit}
    os_detections
    echo -e "------------------------------------" >> ${pathaudit}
    admin
    bootinfo  
    prog
    software
    sshcheck
    firewall
    echo -e "------------------------------------" >>${pathaudit}
    scan
    reco
    echo -e "------------------------------------" >> ${pathaudit}

    echo "maj log:         /usr/share/urnis/data/log-maj" >> ${pathaudit}
    echo "scan log:        ${pathlog}" >> ${pathaudit}
    echo "scan result:     ${pathaudit}" >> ${pathaudit}
    echo -e "------------------------------------" >> ${pathaudit}
    echo -e "${date}" >> ${pathaudit}
    echo -e "\n\n${BLEU}[+] RESULT${NC}\n-----------------------------------\n"
    cat ${pathaudit}
}

look () {
    maj
    timm=$(($tim * 3600))
    while true; do
        sudo sed -i -e 's/urnislstatus="0"/urnislstatus="1"/g' /usr/share/urnis/src/urnis.conf
        audit > ${pathlog}
        sudo python3 /usr/share/urnis/src/mailsender.py ${sender} ${passw} ${reciver} ${pathfilemail}
        sleep $timm
    done
}

remove () {
    echo "Are you sure you want to remove [y/n]"
    read remove_rep
    if [ "$remove_rep" = "y" ]; then
        sudo rm -fr /usr/share/urnis
        echo -e "remove sucessfully" 
        sudo rm -fr /usr/sbin/urnis
    fi
}

kills () {
    sudo ps -a | grep 'urnis' | awk '{print $1}' > /usr/share/urnis/data/kill.txt
    file_path="/usr/share/urnis/data/kill.txt"
    sudo sed -i -e 's/urnislstatus="1"/urnislstatus="0"/g' /usr/share/urnis/src/urnis.conf
    while read -r line; do
        sudo kill -9 $line
    done < "$file_path"
}

update () {
    echo "For update you can execute sudo urnis -r"
    echo "git clone https://github.com/bubudotsh/urnis-security.git"
    echo "run setup.sh and reconfigure urnis"
}

status () {
    lookstatus=$(grep urnislstatus /usr/share/urnis/src/urnis.conf | cut -c 14- | sed 's/"//g')
    if [ "${lookstatus}" = "0" ]; then
        printf "%-40s %s\n" "URNIS LOOK STATUS" "NOT RUN"
    elif [ "${lookstatus}" = "1" ];then
        printf "%-40s %s\n" "URNIS LOOK STATUS" "RUNNING"
    else
        printf "%-40s %s\n" "URNIS LOOK STATUS" "error"
    fi
}

while getopts "huamlrks" option; do
case $option in
    h)
        helper
        exit;;
    u)
        update
        exit;;
    a)
        audit
        exit;;
    m)
        audit
        sudo python3 /usr/share/urnis/src/mailsender.py ${sender} ${passw} ${reciver} ${pathfilemail}
        exit;;
    l)
        look > /dev/null 2> /dev/null
        exit;;
    k)
        kills
        exit;;
    r)
        remove
        exit;;
    s)
        status
        exit;;
    \?)
        echo "bad option, help : -h"
        exit;;
    esac
done
echo "bad option, try sudo urnis -h"